service: sls-az-func-rest-api

provider:
  name: azure
  runtime: nodejs10.x
  region: ${opt:region, 'West US'}
  stage: ${opt:stage, 'dev'}
  prefix: ${opt:prefix, 'demo'}
  apim: true

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  issues:
    handler: src/handlers/issues.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - GET
  pulls:
    handler: src/handlers/pulls.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - GET
