service: sls-az-func-rest-api

provider:
  name: azure
  runtime: nodejs10.x
  region: ${opt:region, 'West US'}
  stage: ${opt:stage, 'dev'}
  prefix: ${opt:prefix, 'demo'}
  apim:
    apis:
      - name: github-api
        subscriptionRequired: false
        displayName: Github API
        description: The GitHub API
        protocols:
          - https
        # Defaults to /api
        path: github
        tags:
          - apimTag1
          - apimTag2
        authorization: none
    backends:
      - name: github-backend
        url: api/github
    cors:
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"

plugins:
  - serverless-azure-functions
  - serverless-webpack

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  issues:
    handler: src/handlers/issues.handler
    apim:
      api: github-api
      backend: github-backend
      operations:
        - method: get
          urlTemplate: /issues
          displayName: GetIssues
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - GET
  pulls:
    handler: src/handlers/pulls.handler
    apim:
      api: github-api
      backend: github-backend
      operations:
        - method: get
          urlTemplate: /pulls
          displayName: GetPullRequests
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - GET
